### PR TITLE
Add test case in which keys start with upper/lower case

### PR DESCRIPTION
**Pull request by leslie-qiwa**
Signed-off-by: Leslie Qi Wang <qiwa@pensando.io>

### CODE REVIEW

**Comment by nqd** [comment]
@leslie-qiwa the MR looks good. Could you please fix the linting? Will merge after that

**Comment by leslie-qiwa** [comment]
@nqd seems like failure is related with downloading one package, not for lint.

```+++ go fmt ./...
[9](https://github.com/nqd/flat/actions/runs/3569461767/jobs/6077347640#step:5:10)
+++ wc -l
[10](https://github.com/nqd/flat/actions/runs/3569461767/jobs/6077347640#step:5:11)
go: downloading github.com/imdario/mergo v0.3.12
[11](https://github.com/nqd/flat/actions/runs/3569461767/jobs/6077347640#step:5:12)
++ exit 1
[12](https://github.com/nqd/flat/actions/runs/3569461767/jobs/6077347640#step:5:13)
Error: Process completed with exit code 1.
```

local run seems good
```
 % go fmt ./...
```

Can we re-run ?

**Comment by nqd** [comment]
you are correct. The CI pipeline was broken. I fixed it

**Pull request merged**
